/// Flutter icons AitChatFonts
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AitChatFonts
///      fonts:
///       - asset: fonts/AitChatFonts.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AitChatFonts {
  AitChatFonts._();

  static const _kFontFam = 'AitChatFonts';

  static const IconData chat = IconData(0xf03d, fontFamily: _kFontFam);
  static const IconData comment = IconData(0xf4ac, fontFamily: _kFontFam);
}
